version: '3'

services:
  sylius:
    container_name: ${NAME}-web
#    image: navidonskis/nginx-php7.1
    build:
        context: .
        args:
          - ENABLE_XDEBUG=${ENABLE_XDEBUG}
    environment:
      - SYLIUS_DATABASE_HOST=mysql
      - SYLIUS_DATABASE_USER=sylius
      - SYLIUS_DATABASE_PASSWORD=sylius
      - SYLIUS_MAILER_HOST=mailhog:1025
      - SYLIUS_APP_DEV_PERMITTED=1
#      - USER=${USER}
#      - PUID=${USER}
#      - PGID=${USER}
    ports:
      - 8000:80
    volumes:
      - ./../project:/var/www/html/sylius
      - ./conf/nginx/nginx.conf:/etc/nginx/sites-available/default.conf
      - ./conf/php/docker-vars.ini:/usr/local/etc/php/conf.d/docker-vars.ini
      - ./conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    restart: always
    working_dir: /var/www/html/sylius

  mysql:
    container_name: ${NAME}-mysql
    image: percona:5.7
    environment:
      MYSQL_ROOT_PASSWORD: sylius
      MYSQL_DATABASE: sylius_dev
      MYSQL_USER: sylius
      MYSQL_PASSWORD: sylius
    ports:
      - 127.0.0.1:3606:3306
    volumes:
      - "${DB_PATH}:/var/lib/mysql"

  mailhog:
    container_name: ${NAME}-mailhog
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025

  phpmyadmin:
    container_name: ${NAME}-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8001:80
    restart: always
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_USER=sylius
      - MYSQL_ROOT_PASSWORD=sylius